version: '3'
services:
  back:
    build: ./back
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./back:/code
    ports:
      - "8000:8000"
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    volumes:
     - ./front:/usr/src/app
    command: sh -c "cd workplace && yarn start"
    ports:
     - "3000:3000"
    tty: true